language: c

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
    - os: osx
      compiler: clang

before_install:
  - test/travis-ci/before-install

before_script:
  - test/travis-ci/before-script

script:
  - test/travis-ci/build
